package com.tencent.mm.storage;

import android.content.Context;
import android.util.SparseArray;
import com.tencent.mm.compatible.util.e;
import com.tencent.mm.sdk.a.b;
import com.tencent.mm.sdk.platformtools.ad;
import com.tencent.mm.sdk.platformtools.bi;
import com.tencent.mm.sdk.platformtools.x;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import junit.framework.Assert;

public final class aa
{
  public static String duN = e.duN;
  public static final String sOs = ad.getContext().getFilesDir() + "/xlog";
  
  static
  {
    if (b.chp()) {
      Assert.assertTrue(ckT());
    }
  }
  
  private static final String XN(String paramString)
  {
    int j = -1;
    String[] arrayOfString = paramString.split("_");
    if ((arrayOfString == null) || (arrayOfString.length < 4))
    {
      if (arrayOfString == null) {}
      for (;;)
      {
        x.e("MicroMsg.ConstantsStorage", "BusinessInfoKey parse failed: key:%s split by '_'  fileds len too short : %d , at least 4", new Object[] { paramString, Integer.valueOf(j) });
        return null;
        j = arrayOfString.length;
      }
    }
    int i = 0;
    while (i < arrayOfString.length)
    {
      if ((arrayOfString[i] == null) || (arrayOfString[i].length() <= 0))
      {
        x.e("MicroMsg.ConstantsStorage", "BusinessInfoKey parse failed: name:%s , [%s] too short ( <1 ) ", new Object[] { paramString, arrayOfString[i] });
        return null;
      }
      i += 1;
    }
    int k = arrayOfString.length - 1;
    String str2 = arrayOfString[k];
    i = k;
    String str1 = str2;
    if (str2.equals("SYNC"))
    {
      i = k - 1;
      str1 = arrayOfString[i];
    }
    if (i < 3) {
      if (arrayOfString != null) {
        break label267;
      }
    }
    for (;;)
    {
      x.e("MicroMsg.ConstantsStorage", "BusinessInfoKey parse failed: name:%s split by '_'  fileds len too short : %d , at least 3", new Object[] { paramString, Integer.valueOf(j) });
      if ((str1.equals("INT")) || (str1.equals("LONG")) || (str1.equals("STRING")) || (str1.equals("BOOLEAN")) || (str1.equals("FLOAT")) || (str1.equals("DOUBLE"))) {
        break;
      }
      x.e("MicroMsg.ConstantsStorage", "BusinessInfoKey parse failed: name[%s], invalid type:%s ", new Object[] { paramString, str1 });
      return null;
      label267:
      j = i;
    }
    return paramString.substring(0, paramString.lastIndexOf(str1) - 1);
  }
  
  private static final boolean ckT()
  {
    Field[] arrayOfField = aa.class.getDeclaredFields();
    SparseArray localSparseArray = new SparseArray();
    int i = 0;
    while (i < arrayOfField.length)
    {
      Field localField = arrayOfField[i];
      if ((Modifier.isStatic(localField.getModifiers())) && ((localField.getName().startsWith("USERINFO_")) || (localField.getName().startsWith("NEW_BANDAGE_")) || (localField.getName().startsWith("DYNAMIC_CONFIG_"))) && (localField.getType().toString().equals("int"))) {}
      try
      {
        int j = localField.getInt(null);
        if (localSparseArray.get(j, null) != null)
        {
          x.e("MicroMsg.ConstantsStorage", "%s and %s has same value(0x%05X)!!!", new Object[] { localSparseArray.get(j), localField.getName(), Integer.valueOf(j) });
          return false;
        }
        localSparseArray.put(j, localField.getName());
      }
      catch (IllegalArgumentException localIllegalArgumentException)
      {
        for (;;)
        {
          x.e("MicroMsg.ConstantsStorage", "exception:%s", new Object[] { bi.i(localIllegalArgumentException) });
        }
      }
      catch (IllegalAccessException localIllegalAccessException)
      {
        for (;;)
        {
          x.e("MicroMsg.ConstantsStorage", "exception:%s", new Object[] { bi.i(localIllegalAccessException) });
        }
      }
      i += 1;
    }
    if (localSparseArray.size() > 511)
    {
      x.e("MicroMsg.ConstantsStorage", "constants values size(%d) is over the limit(%d)!!!", new Object[] { Integer.valueOf(localSparseArray.size()), Integer.valueOf(511) });
      return false;
    }
    x.i("MicroMsg.ConstantsStorage", "checkDuplicateUserInfo values size: %d", new Object[] { Integer.valueOf(localSparseArray.size()) });
    return ckU();
  }
  
  private static final boolean ckU()
  {
    ArrayList localArrayList = new ArrayList(a.values().length);
    a[] arrayOfa = a.values();
    int j = arrayOfa.length;
    int i = 0;
    while (i < j)
    {
      Object localObject = arrayOfa[i];
      if ((localObject == null) || (((a)localObject).name() == null)) {
        x.e("MicroMsg.ConstantsStorage", "BusinessInfoKey check error: info is null!!!");
      }
      do
      {
        return false;
        localObject = XN(((a)localObject).name());
      } while (bi.oW((String)localObject));
      if (localArrayList.contains(localObject))
      {
        x.e("MicroMsg.ConstantsStorage", "BusinessInfoKey check error: redefinition of [%s] which already defined!", new Object[] { localObject });
        return false;
      }
      localArrayList.add(localObject);
      i += 1;
    }
    return true;
  }
  
  public static enum a
  {
    static
    {
      sOA = new a("USERINFO_SHAKE_CARD_ENTRANCE_OPEN_BOOLEAN_SYNC", 7);
      sOB = new a("USERINFO_SHAKE_CARD_ENTRANCE_BEGIN_TIME_INT_SYNC", 8);
      sOC = new a("USERINFO_SHAKE_CARD_ENTRANCE_END_TIME_INT_SYNC", 9);
      sOD = new a("USERINFO_SHAKE_CARD_ENTRANCE_NAME_STRING_SYNC", 10);
      sOE = new a("USERINFO_SHAKE_CARD_FLOW_CONTROL_LEVEL_MIN_INT_SYNC", 11);
      sOF = new a("USERINFO_SHAKE_CARD_FLOW_CONTROL_LEVEL_MAX_INT_SYNC", 12);
      sOG = new a("USERINFO_SHAKE_CARD_ENTRANCE_TIP_STRING_SYNC", 13);
      sOH = new a("USERINFO_SHAKE_CARD_ACTIVITY_TYPE_INT_SYNC", 14);
      sOI = new a("USERINFO_SHAKE_CARD_ENTRANCE_RED_DOT_ID_STRING_SYNC", 15);
      sOJ = new a("USERINFO_SHAKE_CARD_ENTRANCE_RED_DOT_DESC_STRING_SYNC", 16);
      sOK = new a("USERINFO_SHAKE_CARD_ENTRANCE_RED_DOT_TEXT_STRING_SYNC", 17);
      sOL = new a("USERINFO_SHAKE_CARD_TAB_RED_DOT_ID_STRING_SYNC", 18);
      sOM = new a("USERINFO_SHAKE_CARD_TAB_RED_DOT_DESC_STRING_SYNC", 19);
      sON = new a("USERINFO_GAME_SEARCH_LIST_UPDATE_TIME_LONG", 20);
      sOO = new a("USERINFO_GAME_GLOBAL_CONFIG_UPDATE_TIME_LONG", 21);
      sOP = new a("USERINFO_MINIGAME_SEARCH_LIST_UPDATE_TIME_LONG", 22);
      sOQ = new a("USERINFO_EMOJI_BACKUP_OVERSIZE_BOOLEAN", 23);
      sOR = new a("USERINFO_EMOJI_SYNC_STORE_EMOJI_UPLODD_LONG", 24);
      sOS = new a("USERINFO_EMOJI_SYNC_STORE_EMOJI_DOWNLOAD_LONG", 25);
      sOT = new a("USERINFO_EMOJI_RECOVER_CUSTOM_EMOJI_BOOLEAN", 26);
      sOU = new a("USERINFO_EMOJI_SYNC_STORE_EMOJI_UPLODD_FINISH_BOOLEAN", 27);
      sOV = new a("USERINFO_EMOJI_STORE_LAST_REFRESH_TIME_LONG", 28);
      sOW = new a("USERINFO_EMOJI_STORE_RECOMMEND_LAST_UPDATE_TIME_LONG", 29);
      sOX = new a("USERINFO_EMOJI_STORE_NEW_ORIGINAL_BOOLEAN", 30);
      sOY = new a("USERINFO_EMOJI_SYNC_CUSTOM_EMOJI_BATCH_DOWNLOAD_BOOLEAN", 31);
      sOZ = new a("USERINFO_EMOJI_SYNC_STORE_EMOJI_NEW_PANEL_BOOLEAN", 32);
      sPa = new a("USERINFO_EMOJI_STORE_NEW_DESIGNER_EMOJI_BOOLEAN", 33);
      sPb = new a("USERINFO_EMOJI_LAST_BATCH_EMOJI_DOWNLOAD_TIME_2_LONG", 34);
      sPc = new a("USERINFO_EMOJI_CLEAN_TEMP_FILE_TASK_LONG", 35);
      sPd = new a("USERINFO_EMOJI_ENCODE_EMOJI_FILE_TASK_LONG", 36);
      sPe = new a("USERINFO_EMOJI_REPORT_CUSTOM_EMOJI_COUNT_LONG", 37);
      sPf = new a("USERINFO_EMOJI_REWARD_TIP_ENABLE_BOOLEAN", 38);
      sPg = new a("USERINFO_EMOJI_CUREENT_VERSION_INT", 39);
      sPh = new a("USERINFO_EMOJI_UPDATE_EMOJI_GROUP_COUNT_BOOLEAN", 40);
      sPi = new a("USERINFO_EMOJI_NEW_EMOJI_INT", 41);
      sPj = new a("USERINFO_EMOJI_NEW_PANEL_INT", 42);
      sPk = new a("USERINFO_EMOJI_NEW_SUGGEST_INT", 43);
      sPl = new a("USERINFO_EMOJI_EGG_INT", 44);
      sPm = new a("USERINFO_EMOJI_NEW_PANEL_NAME_STRING", 45);
      sPn = new a("USERINFO_LUCKY_MONEY_NEWYEAR_SWITCH_INT_SYNC", 46);
      sPo = new a("USERINFO_LUCKY_MONEY_NEWYEAR_LOCAL_SWITCH_INT", 47);
      sPp = new a("USERINFO_VOICEPRINT_MORE_TAB_DOT_SHOW_BOOLEAN", 48);
      sPq = new a("USERFINO_VOICEPRINT_SETTING_DOT_SHOW_BOOLEAN", 49);
      sPr = new a("USERINFO_VOICEPRINT_SETTING_ACCOUNT_INFO_DOT_SHOW_BOOLEAN", 50);
      sPs = new a("USERINFO_VOICEPRINT_SETTING_ACCOUNT_INFO_NEW_SHOW_BOOLEAN", 51);
      sPt = new a("USERINFO_REPORTNETTYPE_SEQ_LONG", 52);
      sPu = new a("USERINFO_REPORTNETTYPE_LASTREPORT_LONG", 53);
      sPv = new a("USERINFO_SELFINFO_SMALLIMGURL_STRING", 54);
      sPw = new a("USERINFO_SELFINFO_GETPROFILE_TIME_LONG", 55);
      sPx = new a("USERINFO_WALLET_BALANCE_NOTICE_STRING", 56);
      sPy = new a("USERINFO_WALLET_FETCH_NOTICE_STRING", 57);
      sPz = new a("USERINFO_WALLET_SUPPORT_BANK_WORD_STRING", 58);
      sPA = new a("USERINFO_NEED_TO_UPDATE_CONVERSATION_TIME_DIVIDER_LONG", 59);
      sPB = new a("USERINFO_EXPOSE_GETEXPOSESCENE_TIME_LONG", 60);
      sPC = new a("USERINFO_WXPHONE_PB_COUNT_INT", 61);
      sPD = new a("USERINFO_MALL_INDEX_HAS_SHOWN_FTF_NOTICE_BOOLEAN", 62);
      sPE = new a("USERINFO_PHONE_RECHARGE_CLOSED_BANNER_STRING", 63);
      sPF = new a("USERINFO_QQMAIL_UNREAD_COUNT_INT", 64);
      sPG = new a("USERINFO_AUTOGETBIG_IMG_MAX_LONG", 65);
      sPH = new a("USERINFO_AUTOGETBIG_IMG_CURRENT_LONG", 66);
      sPI = new a("USERINFO_AUTOGETBIG_IMG_CURRENT_DATE_LONG", 67);
      sPJ = new a("USERINFO_SHAKE_KV_STAT_BLUETOOTH_POWER_STATE_TIME_LONG", 68);
      sPK = new a("USERINFO_SHAKE_TV_LATITUDE_STRING", 69);
      sPL = new a("USERINFO_SHAKE_TV_LONGTITUDE_STRING", 70);
      sPM = new a("NEW_BANDAGE_DATASOURCE_NEW_CARD_REDDOT_WORDING_STRING_SYNC", 71);
      sPN = new a("NEW_BANDAGE_DATASOURCE_NEW_CARD_ICON_STRING_SYNC", 72);
      sPO = new a("NEW_BANDAGE_WATCHER_SETTING_CARD_ENTRY_REDDOT_WORDING_STRING_SYNC", 73);
      sPP = new a("NEW_BANDAGE_WATCHER_SETTING_CARD_ENTRY_ICON_STRING_SYNC", 74);
      sPQ = new a("USERINFO_CARDLAYOUT_TESTDATA_STRING", 75);
      sPR = new a("USERINFO_CARD_LAYOUT_BUF_DATA_STRING_SYNC", 76);
      sPS = new a("USERINFO_CARD_REDOT_WORDING_STRING_SYNC", 77);
      sPT = new a("USERINFO_CARD_REDOT_END_TIME_INT_SYNC", 78);
      sPU = new a("USERINFO_CARD_REDOT_BUFF_STRING_SYNC", 79);
      sPV = new a("USERINFO_CARD_REDOT_ICON_URL_STRING_SYNC", 80);
      sPW = new a("USERINFO_CARD_MSG_TIPS_TITLE_STRING_SYNC", 81);
      sPX = new a("USERINFO_CARD_MSG_TIPS_ICON_URL_STRING_SYNC", 82);
      sPY = new a("USERINFO_CARD_GET_LAYOUT_SCENE_INT_SYNC", 83);
      sPZ = new a("USERINFO_CARD_GET_LAYOUT_JSON_STRING_SYNC", 84);
      sQa = new a("USERINFO_CARD_SHARECARD_LAYOUT_JSON_STRING_SYNC", 85);
      sQb = new a("USERINFO_CARD_REQUENCE_LONG_SYNC", 86);
      sQc = new a("USERINFO_CARD_IS_SHARE_CARD_ENTRANCE_OPEN_INT_SYNC", 87);
      sQd = new a("USERINFO_CARD_IS_SHOW_SHARE_CARD_TIP_INT_SYNC", 88);
      sQe = new a("USERINFO_CARD_IS_SHOW_SHARE_CARD_ENTRANCE_TIP_INT_SYNC", 89);
      sQf = new a("USERINFO_CARD_IS_SHOW_MEMBERSHIP_TIP_INT_SYNC", 90);
      sQg = new a("USERINFO_CARD_SHARE_LIST_CLEAR_TIME_INT_SYNC", 91);
      sQh = new a("USERINFO_CARD_SHOW_WARNING_CARD_IDS_STRING_SYNC", 92);
      sQi = new a("USERINFO_CARD_HAS_UPDATE_CARD_TYPE_INT_SYNC", 93);
      sQj = new a("USERINFO_CARD_MSG_CARD_ID_STRING_SYNC", 94);
      sQk = new a("USERINFO_CARD_MSG_NEED_CHECK_BOOLEAN_SYNC", 95);
      sQl = new a("USERINFO_POSITION_REMIND_MSG_TIP_IN_BOOLEAN", 96);
      sQm = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_BOOLEAN_SYNC", 97);
      sQn = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_HWFPMANAGER_BOOLEAN_SYNC", 98);
      sQo = new a("USERINFO_WALLET_FINGERPRINT_SWITCH_IS_NOT_NEW_BOOLEAN_SYNC", 99);
      sQp = new a("USERINFO_FINGER_PRINT_IS_OPEN_BOOLEAN_SYNC", 100);
      sQq = new a("USERINFO_FINGER_PRINT_IS_SO_LOAD_SUCCESS_BOOLEAN_SYNC", 101);
      sQr = new a("USERINFO_FINGER_PRINT_IS_FORCE_PWD_MODE_BOOLEAN_SYNC", 102);
      sQs = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_IN_TRANSPARENT_BOOLEAN_SYNC", 103);
      sQt = new a("USERINFO_FINGER_PRINT_IS_SO_LOADLIBRARY_SUCCESS_BOOLEAN_SYNC", 104);
      sQu = new a("USERINFO_FINGER_PRINT_IS_FIRST_SHOWN_BOOLEAN_SYNC", 105);
      sQv = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_IN_TRANSPARENT_NEW_BOOLEAN_SYNC", 106);
      sQw = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_COUNT_INT_SYNC", 107);
      sQx = new a("USERINFO_FINGER_PRINT_LAST_IS_SEVERE_ERROR_BOOLEAN_SYNC", 108);
      sQy = new a("USERINFO_ABTEST_SERVER_TIMESTAMP_INT", 109);
      sQz = new a("USERINFO_ABTEST_LAST_UPDATE_TIME_LONG", 110);
      sQA = new a("USERINFO_ABTEST_UPDATE_TIME_INTERVAL_INT", 111);
      sQB = new a("USERINFO_NFC_CPU_CARD_CONFIG_STRING", 112);
      sQC = new a("USERINFO_BIND_MOBILE_XML_TIP_BOOLEAN", 113);
      sQD = new a("USERINFO_BIND_MOBILE_XML_FORCE_BIND_BOOLEAN", 114);
      sQE = new a("USERINFO_BIND_MOBILE_XML_WORDING_STRING", 115);
      sQF = new a("USERINFO_BIZ_ATTR_SYNC_OPEN_FLAG_INT", 116);
      sQG = new a("USERINFO_NFC_OPEN_SWITCH_INT_SYNC", 117);
      sQH = new a("USERINFO_NFC_OPEN_DEFAULT_SWITCH_INT_SYNC", 118);
      sQI = new a("BUSINESS_SNS_ADLOG_FREQUENCY_INT", 119);
      sQJ = new a("BUSINESS_SNS_ADLOG_CNTTIME_INT", 120);
      sQK = new a("USERINFO_NFC_OPEN_SWITCH_WORDING_STRING_SYNC", 121);
      sQL = new a("USERINFO_SNS_OPEN_UPLOAD_DRAFT_MEDIA_STRING_SYNC", 122);
      sQM = new a("USERINFO_SNS_OPEN_UPLOAD_NEWTEXT_DRAFT_STRING_SYNC", 123);
      sQN = new a("USERINFO_SNS_OPEN_UPLOAD_WEISHI_BOOLEAN_SYNC", 124);
      sQO = new a("USERINFO_SNS_OPEN_SHOW_WEISHI_BOOLEAN_SYNC", 125);
      sQP = new a("USERINFO_IPCALL_COUNTRY_CODE_RESTRCTION_INT", 126);
      sQQ = new a("USERINFO_IPCALL_COUNTRY_CODE_LASTUPDATE_TIME_LONG", 127);
      sQR = new a("USERINFO_IPCALL_FIRST_IN_BOOLEAN", 128);
      sQS = new a("USERINFO_IPCALL_ADDRESS_LASTREPORT_TIME_LONG", 129);
      sQT = new a("USERINFO_IPCALL_ADDRESS_GETMFRIEND_LASTUPDATE_TIME_LONG", 130);
      sQU = new a("USERINFO_IPCALL_ADDRESS_GETLOCATION_LASTUPDATE_TIME_LONG", 131);
      sQV = new a("USERINFO_IPCALL_ADDRESS_ACCOUNT_SHOW_REDDOT_BOOLEAN", 132);
      sQW = new a("USERFINO_IPCALL_ADDRESS_ACCOUNT_SHOW_REDDOT_TYPE_INT", 133);
      sQX = new a("USERFINO_IPCALL_ADDRESS_ACCOUNT_STRING", 134);
      sQY = new a("USERFINO_IPCALL_ADDRESS_ACCOUNT_ACTIVITY_STRING", 135);
      sQZ = new a("USERINFO_IPCALL_ADDRESS_ACCOUNT_ACTIVITY_CLEAR_TYPE_INT", 136);
      sRa = new a("USERINFO_IPCALL_ADDRESS_ACCOUNT_ACTIVITY_TYPE_VERSION_INT", 137);
      sRb = new a("USERFINO_IPCALL_RECHARGE_STRING", 138);
      sRc = new a("USERINFO_IPCALL_RECHARGE_SHOW_REDDOT_BOOLEAN", 139);
      sRd = new a("USERINFO_IPCALL_PACKAGE_PURCHASE_STRING", 140);
      sRe = new a("USERINFO_IPCALL_EXCHANGE_RECORD_SHOW_REDDOT_BOOLEAN", 141);
      sRf = new a("USERFINO_IPCALL_HAS_ENTRY_BOOLEAN", 142);
      sRg = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_REDDOT_INT", 143);
      sRh = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_WORDING_STRING", 144);
      sRi = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_REDDOT_NEWXML_BOOLEAN", 145);
      sRj = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_REDDOT_TYPE_INT", 146);
      sRk = new a("USERINFO_IPCALL_MSG_CENTER_SHOW_REDDOT_BOOLEAN", 147);
      sRl = new a("USERFINO_IPCALL_MSG_CENTER_SHOW_REDDOT_TYPE_INT", 148);
      sRm = new a("USERFINO_IPCALL_REDDOT_RECHARGE_VERSION_INT", 149);
      sRn = new a("USERFINO_IPCALL_SHOW_FROM_VOIP_LAST_TIME_LONG", 150);
      sRo = new a("USERFINO_IPCALL_SHOW_FROM_VOIP_TIME_COUNT_INT", 151);
      sRp = new a("USERFINO_FAV_HAS_DB_DATATOTALLENGTH_BOOLEAN", 152);
      sRq = new a("USERFINO_FAV_USED_CAPACITY_LONG", 153);
      sRr = new a("USERFINO_FAV_TOTAL_CAPACITY_LONG", 154);
      sRs = new a("USERFINO_FAV_IS_FULL_BOOLEAN", 155);
      sRt = new a("USERFINO_IPCALL_SHOW_FEEDBACK_LAST_TIME_LONG", 156);
      sRu = new a("USERFINO_IPCALL_SHOW_FEEDBACK_TIME_COUNT_INT", 157);
      sRv = new a("USERFINO_IPCALL_HAS_ACTIVITY_BOOLEAN", 158);
      sRw = new a("USERFINO_IPCALL_ACTIVITY_STRING", 159);
      sRx = new a("USERINFO_SUBMENU_SHOW_TIT_BOOLEAN", 160);
      sRy = new a("USERINFO_PROFILE_WEIDIANINFO_STRING", 161);
      sRz = new a("GAME_DISCOVERY_ENTRANCE_MSGID_LONG_SYNC", 162);
      sRA = new a("GAME_INDEX_BUBBLE_MSGID_LONG_SYNC", 163);
      sRB = new a("GAME_MSG_ENTRANCE_MSGID_LONG_SYNC", 164);
      sRC = new a("GAME_GIFT_ENTRANCE_MSGID_LONG_SYNC", 165);
      sRD = new a("GAME_INDEX_FLOATLAYER_MSGID_LONG_SYNC", 166);
      sRE = new a("USERINFO_WELCOMEMSG_CONTENT_STRING", 167);
      sRF = new a("USERINFO_WELCOMEMSG_EXT_LASTTIME_LONG", 168);
      sRG = new a("USERINFO_WELCOMEMSG_EXT_SHOWCOUNT_LONG", 169);
      sRH = new a("USERINFO_RES_DOWNLOADER_CHECK_RES_UPDATE_INTERVAL_LONG", 170);
      sRI = new a("USERINFO_RES_DOWNLOADER_CHECK_RESUME_INTERVAL_LONG", 171);
      sRJ = new a("USERINFO_LOAN_ENTRANCE_RED_POINT_INT", 172);
      sRK = new a("USERINFO_WEBVIEW_CLEAR_HOST_COOKIES_INTERVAL_LONG", 173);
      sRL = new a("USERINFO_IBEACON_PUSH_SHOP_ID_LONG", 174);
      sRM = new a("USERINFO_IBEACON_PUSH_CHANNEL_OPEN_METHOD_INT", 175);
      sRN = new a("USERINFO_IBEACON_PUSH_CHANNEL_OPEN_TIME_LONG", 176);
      sRO = new a("USERINFO_IBEACON_SHAKE_TAB_DISPLAY_INT", 177);
      sRP = new a("USERINFO_IBEACON_SHAKE_IS_RANGING_INTERFACE_BOOLEAN", 178);
      sRQ = new a("USERINFO_IBEACON_PUSH_BEACONINFO_STRING", 179);
      sRR = new a("USERINFO_IBEACON_PUSH_LAST_BEACONINFO_STRING", 180);
      sRS = new a("USERINFO_IBEACON_PUSH_IS_OPEN_BOOLEAN", 181);
      sRT = new a("USERINFO_IBEACON_PUSH_OPEN_TIEMSTAMP_LONG", 182);
      sRU = new a("USERINFO_IBEACON_PUSH_IS_IN_SHAKEUI_BOOLEAN", 183);
      sRV = new a("USERINFO_IBEACON_SHAKE_TAB_IS_BLUETOOTH_RESIDENT_BOOLEAN", 184);
      sRW = new a("USERINFO_IBEACON_SHAKE_TAB_IS_CITY_RESIDENT_BOOLEAN", 185);
      sRX = new a("USERINFO_IBEACON_SHAKE_TAB_IS_UIN_RESIDENT_INT", 186);
      sRY = new a("USERINFO_IBEACON_SHAKE_TAB_RESIDENT_GATED_LAUNCH_INT", 187);
      sRZ = new a("USERINFO_PROFILE_WEIDIANINFO_ALERT_INT", 188);
      sSa = new a("USERINFO_LAST_LOCATION_STRING", 189);
      sSb = new a("USERINFO_LAST_F2F_INVITE_TIME_LONG", 190);
      sSc = new a("USERINFO_F2F_DELAY_TIME_LONG", 191);
      sSd = new a("USERINFO_MALL_INDEX_TYPE_NAME_LIST_STRING_SYNC", 192);
      sSe = new a("USERINFO_MALL_THIRD_PARTY_DISCLAIMER_STRING", 193);
      sSf = new a("USERINFO_SHAKE_TV_ACCURACY_STRING", 194);
      sSg = new a("USERINFO_IPCALL_ACCOUNT_CACHE_STRING", 195);
      sSh = new a("USERINFO_SET_CAN_WEBVIEW_CACHE_DOWNLOAD_BOOLEAN", 196);
      sSi = new a("USERINFO_SET_CAN_WEBVIEW_CACHE_PRE_PUSH_DOWNLOAD_BOOLEAN", 197);
      sSj = new a("USERINFO_WEBVIEW_CACHE_CLEANUP_INTERVAL_LONG", 198);
      sSk = new a("USERINFO_TRICK_SOTER_BOOLEAN", 199);
      sSl = new a("USERINFO_CLEANUI_QQMGRINFO_STRING", 200);
      sSm = new a("USERINFO_POSITION_AT_CHATRECORD_FIRST_IN_BOOLEAN", 201);
      sSn = new a("USERINFO_POSITION_INVOKE_EDIT_TIP_IN_BOOLEAN", 202);
      sSo = new a("USERINFO_HAD_SHOW_WALLET_MULTI_WALLET_GUIDE_BOOLEAN", 203);
      sSp = new a("USERINFO_WALLET_BULLETIN_GET_TIME_LONG", 204);
      sSq = new a("USERINFO_WALLET_BULLETIN_UPDATE_INTERVAL_LONG", 205);
      sSr = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRL_STRING_SYNC", 206);
      sSs = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_TIP_STRING_SYNC", 207);
      sSt = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKFINDMORE_STRING_SYNC", 208);
      sSu = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKCAMERA_STRING_SYNC", 209);
      sSv = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKFULLSCREEN_STRING_SYNC", 210);
      sSw = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYOPEN_BOOLEAN_SYNC", 211);
      sSx = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYCTRLHASSHOW_BOOLEAN_SYNC", 212);
      sSy = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYCOUNT_INT_SYNC", 213);
      sSz = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYCOUNT2_INT_SYNC", 214);
      sSA = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKPOST_STRING_SYNC", 215);
      sSB = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKGOLDCAMERATIP_STRING_SYNC", 216);
      sSC = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_TIPMARKCAMERATIP_STRING_SYNC", 217);
      sSD = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_LEVELCTRL_STRING_SYNC", 218);
      sSE = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_FLOW_CONTROL_CACHEBUFFER_STRING", 219);
      sSF = new a("USERINFO_NEWYEAR_2016_ACCEPT_CARD_ITEM_BUFFER_STRING_SYNC", 220);
      sSG = new a("USERINFO_NEWYEAR_2016_HONGBAO_IS_OPEN_SNS_PAY_INT_SYNC", 221);
      sSH = new a("USERINFO_NEWYEAR_2016_HONGBAO_CAN_OPEN_SNS_PAY_INT_SYNC", 222);
      sSI = new a("USERINFO_NEWYEAR_2016_HONGBAO_IS_WHITE_USER_INT_SYNC", 223);
      sSJ = new a("USERINFO_NEWYEAR_2016_HONGBAO_OPEN_SNS_PAY_TITLE_STRING_SYNC", 224);
      sSK = new a("USERINFO_NEWYEAR_2016_HONGBAO_OPEN_SNS_PAY_WORDING_STRING_SYNC", 225);
      sSL = new a("USERINFO_NEWYEAR_2016_HONGBAO_SET_SNS_PAY_TITLE_STRING_SYNC", 226);
      sSM = new a("USERINFO_NEWYEAR_2016_HONGBAO_SET_SNS_PAY_WORDING_STRING_SYNC", 227);
      sSN = new a("USERINFO_NEWYEAR_2016_HONGBAO_HAS_SHOW_SNS_PAY_GUIDE_DIALOG_BOOLEAN_SYNC", 228);
      sSO = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_PATH_STRING_SYNC", 229);
      sSP = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_ID_STRING_SYNC", 230);
      sSQ = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_AES_KEY_STRING_SYNC", 231);
      sSR = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_LENGTH_INT_SYNC", 232);
      sSS = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_PRESTRAIN_FLAG_INT_SYNC", 233);
      sST = new a("USERINFO_FINGERPRINT_RETRY_TIME_INT_SYNC", 234);
      sSU = new a("USERINFO_FINGERPRINT_LAST_FREEZE_TIME_LONG_SYNC", 235);
      sSV = new a("USERINFO_OVER_SEA_DOWNLOAD_X5_HAS_NOTIFY_BOOLEAN_SYNC", 236);
      sSW = new a("USERINFO_WALLET_PAY_DEDUCT_IS_NEW_BOOLEAN_SYNC", 237);
      sSX = new a("USERINFO_WALLET_FETCH_CHARGE_TIP_DIALOG_BOOLEAN_SYNC", 238);
      sSY = new a("USERINFO_WALLET_PREF_INFO_CACHE_TIME_LONG_SYNC", 239);
      sSZ = new a("USERINFO_WALLET_PREF_INFO_EXPIRES_INT_SYNC", 240);
      sTa = new a("USERINFO_WALLET_BANKCARD_DETAIL_URL_STRING_SYNC", 241);
      sTb = new a("USERINFO_WALLET_BANKCARD_DETAIL_URL_TIMESTAMP_LONG_SYNC", 242);
      sTc = new a("USERINFO_WALLET_REALNAME_SWITCH_WORDING_STRING_SYNC", 243);
      sTd = new a("USERINFO_WALLET_REALNAME_DISCLAIMER_QUERY_EXPIRED_TIME_LONG_SYNC", 244);
      sTe = new a("USERINFO_WALLET_DISCLAIMER_NEED_AGERR_INT_SYNC", 245);
      sTf = new a("USERINFO_WALLET_REALNAME_URL_STRING_SYNC", 246);
      sTg = new a("USERINFO_WALLET_LBS_REPORT_DIALOG_SHOW_TIME_LONG_SYNC", 247);
      sTh = new a("USERINFO_WALLET_LBS_REPORT_CONFIG_STRING_SYNC", 248);
      sTi = new a("USERINFO_WALLET_LBS_REPORT_DIALOG_TITLE_STRING_SYNC", 249);
      sTj = new a("USERINFO_WALLET_LBS_REPORT_DIALOG_CONTENT_STRING_SYNC", 250);
      sTk = new a("USERINFO_WALLET_RELEAY_NAME_TIP_CONTENT_STRING_SYNC", 251);
      sTl = new a("USERINFO_WALLET_RELEAY_NAME_BALANCE_CONTENT_STRING_SYNC", 252);
      sTm = new a("USERINFO_WALLET_DEDUCT_SELECT_WORDING_STRING", 253);
      sTn = new a("USERINFO_WALLET_DEDUCT_CHANGE_WORDING_STRING", 254);
      sTo = new a("USERINFO_WALLET_DEDUCT_FORGET_URL_STRING", 255);
      sTp = new a("USERINFO_MINIQB_SUPPORT_FILE_TYPE_STRING_SYNC", 256);
      sTq = new a("USERINFO_FACE_DETECTION_ENROLLED_BOOLEAN_SYNC", 257);
      sTr = new a("USERINFO_WALLET_MALLINDEX_OSDATA_TYPE_STRING_SYNC", 258);
      sTs = new a("USERINFO_WALLET_REGION_TYPE_INT_SYNC", 259);
      sTt = new a("USERINFO_RECHARGE_SHOW_REMIND_BOOLEAN", 260);
      sTu = new a("USERINFO_APP_BRAND_PUBLIC_LIB_UPDATE_NEXT_TIME_SEC_LONG", 261);
      sTv = new a("USERINFO_APP_BRAND_PUBLIC_LIB_USERNAME_STRING", 262);
      sTw = new a("USERINFO_APP_BRAND_PUBLIC_LIB_APPID_STRING", 263);
      sTx = new a("USERINFO_APP_BRAND_PRUNE_PKG_NEXT_TIME_SEC_LONG", 264);
      sTy = new a("USERINFO_APP_BRAND_USAGE_RECORD_SYNC_NEXT_TIME_SEC_LONG", 265);
      sTz = new a("USERINFO_APP_BRAND_USAGE_RECORD_HAS_FAVORITE_BOOLEAN", 266);
      sTA = new a("USERINFO_APP_BRAND_USAGE_RECORD_HAS_HISTORY_BOOLEAN", 267);
      sTB = new a("USERINFO_APP_BRAND_SHOW_HISTORY_COUNT_BOOLEAN", 268);
      sTC = new a("USERINFO_APP_BRAND_HISTORY_HAS_MORE_BOOLEAN", 269);
      sTD = new a("USERINFO_APP_BRAND_HISTORY_LIST_PAGING_LAST_SERVER_MIN_UPDATE_TIME_LONG", 270);
      sTE = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_END_TIME_SECOND_LONG", 271);
      sTF = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_NEW_XML_MSG_ID_STRING", 272);
      sTG = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_NEW_XML_PUSH_TIME_LONG", 273);
      sTH = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_NEW_XML_SHOWTYPE_INT", 274);
      sTI = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_NEW_XML_REASON_INT", 275);
      sTJ = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_TIPS_STRING", 276);
      sTK = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_HAS_REPORTED_SEE_RED_DOT_BOOLEAN", 277);
      sTL = new a("USERINFO_APP_BRAND_ENTRANCE_SHOW_NEW_BOOLEAN", 278);
      sTM = new a("USERINFO_APP_BRAND_ENTRANCE_LOCATION_REPORT_MSG_ID_STRING", 279);
      sTN = new a("USERINFO_APP_BRAND_ENTRANCE_LOCATION_REPORT_END_TIME_SECOND_LONG", 280);
      sTO = new a("USERINFO_APP_BRAND_ENTRANCE_LOCATION_REPORT_LAST_TIME_SECOND_LONG", 281);
      sTP = new a("USERINFO_APP_BRAND_ENTRANCE_LOCATION_REPORT_FREQUENCY_SECOND_LONG", 282);
      sTQ = new a("USERINFO_APP_BRAND_ENTRANCE_SHOW_RED_DOT_ONCE_BOOLEAN", 283);
      sTR = new a("USERINFO_APP_BRAND_ENTRANCE_HAS_SEEN_NEARBY_SHOWCASE_BOOLEAN_SYNC", 284);
      sTS = new a("USERINFO_APP_BRAND_CHATTING_BANNER_INFO_STRING_SYNC", 285);
      sTT = new a("USERINFO_APP_BRAND_SEARCH_SHOW_OUT_DAILY_SYNC_LAST_TIME_SECOND_LONG", 286);
      sTU = new a("USERINFO_APP_BRAND_RECENT_BAR_HAS_BEEN_REVEALED_BY_FIRST_APP_LAUNCH_BOOLEAN", 287);
      sTV = new a("APPBRAND_PREDOWNLOAD_CGI_PULL_LAST_TIME_IN_SECOND_LONG", 288);
      sTW = new a("APPBRAND_PREDOWNLOAD_DONE_USAGE_USERNAME_DUPLICATE_BEFORE_BOOLEAN_SYNC", 289);
      sTX = new a("APPBRAND_SHORTCUT_URL_UPGRADE_FIXED_BOOLEAN_SYNC", 290);
      sTY = new a("APPBRAND_TBS_CHECK_INSTALL_LAST_TIME_IN_SECOND_LONG", 291);
      sTZ = new a("APPBRAND_BLOCK_QRCODE_PREFIX_STRING_SYNC", 292);
      sUa = new a("USERINFO_EXT_SPORT_PKGNAME_STRING", 293);
      sUb = new a("USERINFO_SENSE_WHERE_LOCATION_STRING", 294);
      sUc = new a("USERINFO_LAST_GET_SENSE_WHERE_LOCATION_LONG", 295);
      sUd = new a("USERINFO_LAST_START_SENSE_WHERE_LONG", 296);
      sUe = new a("USERINFO_REPORT_SD_STATUS_TIME_LONG", 297);
      sUf = new a("USERINFO_REPORT_HARDCODER_TIME_LONG", 298);
      sUg = new a("USERINFO_ADDRESS_HAS_SHOW_DISCLAIMER_DIALOG_BOOLEAN_SYNC", 299);
      sUh = new a("USERINFO_INVOICE_HAS_SHOW_DISCLAIMER_DIALOG_BOOLEAN_SYNC", 300);
      sUi = new a("USERINFO_ONLINE_VIDEO_INT", 301);
      sUj = new a("USERINFO_ADDRESS_HAS_SHOW_WALLETOFFLINE_DIALOG_BOOLEAN_SYNC", 302);
      sUk = new a("USERINFO_SERVICE_NOTIFY_MESSAGE_NOTICE_BOOLEAN_SYNC", 303);
      sUl = new a("USERINFO_WXA_CUSTOM_SESSION_MESSAGE_NOTICE_BOOLEAN_SYNC", 304);
      sUm = new a("USERINFO_WALLETDIGITAL_CERT_CRT_STRING_SYNC", 305);
      sUn = new a("USERINFO_WALLETDIGITAL_CERT_NO_STRING_SYNC", 306);
      sUo = new a("USERINFO_WALLETDIGITAL_CERT_SHOW_INT_SYNC", 307);
      sUp = new a("USERINFO_ADDRESS_HAS_SHOW_WALLETOFFLINE2_DIALOG_BOOLEAN_SYNC", 308);
      sUq = new a("USERINFO_AA_MAX_PAYER_NUM_INT", 309);
      sUr = new a("USERINFO_AA_MAX_RECEIVER_NUM_INT", 310);
      sUs = new a("USERINFO_AA_MAX_TOTAL_USER_NUM_INT", 311);
      sUt = new a("USERINFO_AA_MAX_TOTAL_AMOUNT_LONG", 312);
      sUu = new a("USERINFO_AA_MAX_PER_AMOUNT_LONG", 313);
      sUv = new a("USERINFO_APP_BRAND_FAILED_FORMID_STRING", 314);
      sUw = new a("USERINFO_LOCAL_SIGHT_RECODER_INT_SYNC", 315);
      sUx = new a("USERINFO_LOCAL_SIGHT_ENCODEINSEND_INT_SYNC", 316);
      sUy = new a("USERINFO_LOCAL_SIGHT_PREWVIEWSIZE_INT_SYNC", 317);
      sUz = new a("USERINFO_LOCAL_SIGHT_BITRATE_INT_SYNC", 318);
      sUA = new a("USERINFO_LOCAL_SIGHT_DEBUGINFO_INT_SYNC", 319);
      sUB = new a("USERINFO_LOCAL_SIGHT_SET_SHUTTER_SOUND_INT_SYNC", 320);
      sUC = new a("USERINFO_LOCAL_SIGHT_CROP_INT_SYNC", 321);
      sUD = new a("USERINFO_LOCAL_SIGHT_OPENOLDSIGHT_INT_SYNC", 322);
      sUE = new a("USERINFO_LOCAL_SIGHT_SETTING_PRESET_INT_SYNC", 323);
      sUF = new a("USERINFO_LOCAL_SIGHT_THREADCOUNT_INT_SYNC", 324);
      sUG = new a("USERINFO_LOCAL_SIGHT_REALSCALE_INT_SYNC", 325);
      sUH = new a("USERINFO_LOCAL_SIGHT_FOCUS_INT_SYNC", 326);
      sUI = new a("USERINFO_LOCAL_SIGHT_FFMMPEGCUT_INT_SYNC", 327);
      sUJ = new a("USERINFO_LOCAL_SIGHT_COMPRESS_TO_SINGLE_CHANNEL_INT_SYNC", 328);
      sUK = new a("USERINFO_LOCAL_SIGHT_CLIP_PREVIEW_MEDIA_PLAYER_INT_SYNC", 329);
      sUL = new a("USERINFO_LOCAL_SIGHT_AUDIO_RECORDER_TYPE_INT_SYNC", 330);
      sUM = new a("USERINFO_MMSIGHT_MEDIACODEC_COLORFORMAT_INT", 331);
      sUN = new a("USERINFO_WECHAT_DB_REPORT_LAST_TIME_LONG", 332);
      sUO = new a("USERINFO_CLOG_SAMPLING_REFRESH_TIME_LONG", 333);
      sUP = new a("USERINFO_AVATAR_LAST_MIGRATION_FINISH_LONG", 334);
      sUQ = new a("USERINFO_WECHAT_FILE_SCAN_LAST_TIME_LONG", 335);
      sUR = new a("USERINFO_WECHAT_FILE_SCAN_INTERVAL_LONG", 336);
      sUS = new a("USERINFO_WECHAT_FILE_SCAN_WAIT_TIME_LONG", 337);
      sUT = new a("USERINFO_INSTALL_FIRST_TIME_LONG", 338);
      sUU = new a("USERINFO_INSTALL_FIRST_CLIENT_VERSION_INT", 339);
      sUV = new a("USERINFO_INSTALL_LAST_REPORT_TIME_LONG", 340);
      sUW = new a("USERINFO_MSG_SYNCHRONIZE_BOOLEAN", 341);
      sUX = new a("USERINFO_LOGIN_EXT_DEVICE_INFO_INT", 342);
      sUY = new a("USERINFO_BACKUP_PC_BACKUPING_BOOLEAN", 343);
      sUZ = new a("USERINFO_BACKUP_PC_RECOVERING_BOOLEAN", 344);
      sVa = new a("USERINFO_BACKUP_PC_MERGERING_BOOLEAN", 345);
      sVb = new a("USERINFO_BACKUP_MOVE_BACKUPING_BOOLEAN", 346);
      sVc = new a("USERINFO_BACKUP_MOVE_RECOVERING_BOOLEAN", 347);
      sVd = new a("USERINFO_BACKUP_MOVE_MERGERING_BOOLEAN", 348);
      sVe = new a("USERINFO_BACKUP_OLD_RECORDS_BOOLEAN", 349);
      sVf = new a("USERINFO_WECHAT_BACKUP_CHAT_SIZE_CALCULATE_LAST_TIME_LONG", 350);
      sVg = new a("USERINFO_WECHAT_BACKUP_CHAT_SIZE_CALCULATE_INTERVAL_LONG", 351);
      sVh = new a("USERINFO_WECHAT_BACKUP_CHAT_SIZE_CALCULATE_WAIT_TIME_LONG", 352);
      sVi = new a("USERINFO_DELAY_TRANSFER_CONFIRM_WORDING_STRING", 353);
      sVj = new a("USERINFO_DELAY_TRANSFER_SWITCH_WORDING_STRING", 354);
      sVk = new a("USERINFO_DELAY_TRANSFER_REMIND_WORDING_STRING", 355);
      sVl = new a("USERINFO_DELAY_TRANSFER_EXPIRE_TIME_LONG", 356);
      sVm = new a("USERINFO_DELAY_TRANSFER_DESC_URL_STRING", 357);
      sVn = new a("USERINFO_DELAY_TRANSFER_DESC_URL_FLAG_INT", 358);
      sVo = new a("USERINFO_DELAY_TRANSFER_SHOW_SWITCH_FLAG_INT", 359);
      sVp = new a("USERINFO_WEIXIN_MUL_TERMINAL_AUTOSYNC_BOOLEAN", 360);
      sVq = new a("USERINFO_WEIXIN_CAMERA_STATE_INT", 361);
      sVr = new a("USERINFO_WEIXIN_CAMERASAVEIMAGE_STATE_BOOLEAN", 362);
      sVs = new a("USERINFO_WEIXIN_CAMERASAVEVIDEO_STATE_BOOLEAN", 363);
      sVt = new a("USERINFO_WALLET_REMITTANCE_STRING_SYNC", 364);
      sVu = new a("USERINFO_WALLET_HONGBAO_STRING_SYNC", 365);
      sVv = new a("USERINFO_WEBVIEW_KEEP_STRING_SYNC", 366);
      sVw = new a("USERINFO_WEBVIEW_KEEP_LAST_PAGE_STRING_SYNC", 367);
      sVx = new a("USERINFO_WEBVIEW_KEEP_LAST_PAGE_TITLE_STRING_SYNC", 368);
      sVy = new a("USERINFO_F2F_RING_TONE_STRING", 369);
      sVz = new a("USERINFO_WXA_SEARCH_INPUT_HINT_LANG_STRING_SYNC", 370);
      sVA = new a("USERINFO_WXA_SEARCH_INPUT_HINT_CONTENT_STRING_SYNC", 371);
      sVB = new a("USERINFO_WXA_SEARCH_INPUT_HINT_CONTENT_ID_STRING_SYNC", 372);
      sVC = new a("USERINFO_WXA_SEARCH_INPUT_HINT_UPDATE_TIME_LONG_SYNC", 373);
      sVD = new a("USERINFO_SHAKE_NEWYEAR_COOKIE_STRING", 374);
      sVE = new a("USERINFO_SNS_RECENT_LIMITED_ID_LONG_SYNC", 375);
      sVF = new a("USERINFO_VIDEO_NEED_RESET_EXTRACTOR_BOOLEAN", 376);
      sVG = new a("USERINFO_MALL_NEWS_MARKED_STRING_SYNC", 377);
      sVH = new a("USERINFO_LAUNCH_APP_NOT_ASK_PKG_STRING", 378);
      sVI = new a("USERINFO_WEBVIEW_KEEP_TOP_SCENE_INT_SYNC", 379);
      sVJ = new a("USERINFO_SNS_INTRODUCE_SETTING_DISPLAY_BOOLEAN_SYNC", 380);
      sVK = new a("USERINFO_FACE_SHOW_TUTORIAL_BOOLEAN_SYNC", 381);
      sVL = new a("USERINFO_GAME_WEBVIEW_KEEP_LAST_PAGE_URL_STRING_SYNC", 382);
      sVM = new a("USERINFO_GAME_WEBVIEW_KEEP_LAST_PAGE_USERNAME_STRING_SYNC", 383);
      sVN = new a("USERINFO_GAME_WEBVIEW_KEEP_LAST_PAGE_TITLE_STRING_SYNC", 384);
      sVO = new a("USERINFO_HEAVY_USER_FLAG_LONG", 385);
      sVP = new a("USERINFO_HEAVY_USER_REPORT_TIME_LONG", 386);
      sVQ = new a("USERINFO_HEAVY_USER_REPORT_TYPE_SD_FILE_SIZE_LONG", 387);
      sVR = new a("USERINFO_HEAVY_USER_REPORT_TYPE_SD_FILE_RATIO_LONG", 388);
      sVS = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_SIZE_LONG", 389);
      sVT = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_MESSAGE_LONG", 390);
      sVU = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_CONVERSATION_LONG", 391);
      sVV = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_CONTACT_LONG", 392);
      sVW = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_CHATROOM_LONG", 393);
      sVX = new a("USERINFO_HEAVY_USER_REPORT_TYPE_FAV_DB_SIZE_LONG", 394);
      sVY = new a("USERINFO_MM_LVFETIME_REPORT_PID_INT", 395);
      sVZ = new a("USERINFO_MM_LVFETIME_REPORT_LIFETIME_LONG", 396);
      sWa = new a("USERINFO_MM_LVFETIME_REPORT_MEMORY_PSS_INT", 397);
      sWb = new a("USERINFO_X264_VERSION_INT", 398);
      sWc = new a("USERINFO_SETTING_RECENT_RED_DOT_ID_INT", 399);
      sWd = new a("USERINFO_MY_RED_DOT_WILL_SHOW_ID_INT", 400);
      sWe = new a("USERINFO_MY_RED_DOT_DID_SHOW_ID_INT", 401);
      sWf = new a("USERINFO_SETTING_RED_DOT_WILL_SHOW_ID_INT", 402);
      sWg = new a("USERINFO_SETTING_RED_DOT_DID_SHOW_ID_INT", 403);
      sWh = new a("USERINFO_PRIVATY_RED_DOT_WILL_SHOW_ID_INT", 404);
      sWi = new a("USERINFO_PRIVATY_RED_DOT_DID_SHOW_ID_INT", 405);
      sWj = new a("USERINFO_RECENT_RED_DOT_WILL_SHOW_ID_INT", 406);
      sWk = new a("USERINFO_RECENT_RED_DOT_DID_SHOW_ID_INT", 407);
      sWl = new a("USERINFO_WEIXIN_ENABLEFPSTOOL_STATE_BOOLEAN", 408);
      sWm = new a("USERINFO_CONTINUE_TEST_SCAN_TIME_INT", 409);
      sWn = new a("USERINFO_ABOUT_INVOICE_ENTRANCE_BOOLEAN", 410);
      sWo = new a("USERINFO_MUSIO_LAST_SCAN_MUSIC_PIECE_FILE_TIME_LONG", 411);
      sWp = new a("USERINFO_MUSIO_LAST_SCAN_MUSIC_FILE_TIME_LONG", 412);
      sWq = new a("USERINFO_MUSIC_PLAYER_SWITCH_FLAG_INT_SYNC", 413);
      sWr = new a("USERINFO_MUSIC_SUPPORT_PLAYER_FLAG_SEQUENCE_LONG_SYNC", 414);
      sWs = new a("USERINFO_MUSIC_RREMOVE_PLAYING_AUDIO_PLAYER_GROUP_COUNT_INT_SYNC", 415);
      sWt = new a("USERINFO_MUSIC_SHOW_AUDIO_TOAST_BOOLEAN_SYNC", 416);
      sWu = new a("USERINFO_WEB_SEARCH_CONFIG_ZH_CN_STRING", 417);
      sWv = new a("USERINFO_WEB_SEARCH_CONFIG_ZH_TW_STRING", 418);
      sWw = new a("USERINFO_WEB_SEARCH_CONFIG_ZH_HK_STRING", 419);
      sWx = new a("USERINFO_WEB_SEARCH_CONFIG_EN_STRING", 420);
      sWy = new a("USERINFO_WEB_SEARCH_CONFIG_AR_STRING", 421);
      sWz = new a("USERINFO_WEB_SEARCH_CONFIG_DE_STRING", 422);
      sWA = new a("USERINFO_WEB_SEARCH_CONFIG_DE_DE_STRING", 423);
      sWB = new a("USERINFO_WEB_SEARCH_CONFIG_ES_STRING", 424);
      sWC = new a("USERINFO_WEB_SEARCH_CONFIG_FR_STRING", 425);
      sWD = new a("USERINFO_WEB_SEARCH_CONFIG_HE_STRING", 426);
      sWE = new a("USERINFO_WEB_SEARCH_CONFIG_HI_STRING", 427);
      sWF = new a("USERINFO_WEB_SEARCH_CONFIG_ID_STRING", 428);
      sWG = new a("USERINFO_WEB_SEARCH_CONFIG_IN_STRING", 429);
      sWH = new a("USERINFO_WEB_SEARCH_CONFIG_IT_STRING", 430);
      sWI = new a("USERINFO_WEB_SEARCH_CONFIG_IW_STRING", 431);
      sWJ = new a("USERINFO_WEB_SEARCH_CONFIG_JA_STRING", 432);
      sWK = new a("USERINFO_WEB_SEARCH_CONFIG_KO_STRING", 433);
      sWL = new a("USERINFO_WEB_SEARCH_CONFIG_LO_STRING", 434);
      sWM = new a("USERINFO_WEB_SEARCH_CONFIG_MS_STRING", 435);
      sWN = new a("USERINFO_WEB_SEARCH_CONFIG_MY_STRING", 436);
      sWO = new a("USERINFO_WEB_SEARCH_CONFIG_PL_STRING", 437);
      sWP = new a("USERINFO_WEB_SEARCH_CONFIG_PT_STRING", 438);
      sWQ = new a("USERINFO_WEB_SEARCH_CONFIG_RU_STRING", 439);
      sWR = new a("USERINFO_WEB_SEARCH_CONFIG_TH_STRING", 440);
      sWS = new a("USERINFO_WEB_SEARCH_CONFIG_TR_STRING", 441);
      sWT = new a("USERINFO_WEB_SEARCH_CONFIG_VI_STRING", 442);
      sWU = new a("USERINFO_CLIENT_SERVER_DIFF_TIME_LONG", 443);
      sWV = new a("USERINFO_MSG_DELAY_STAT_STRING", 444);
      sWW = new a("USERINFO_SET_SUPPORT_WX_CODE_BOOLEAN", 445);
      sWX = new a("USERINFO_TENCENT_MAP_COUNT_INT", 446);
      sWY = new a("USERINFO_CROWDTEST_CLIENT_VERSION_INT", 447);
      sWZ = new a("USERINFO_CROWDTEST_APPLY_EXPIRE_LONG", 448);
      sXa = new a("USERINFO_CROWDTEST_APPLY_LINK_STRING", 449);
      sXb = new a("USERINFO_CROWDTEST_FEEDBACK_LINK_STRING", 450);
      sXc = new a("USERINFO_SETTING_PLUGIN_SWITCH_REDDOT_INT", 451);
      sXd = new a("USERINFO_SETTING_PLUGIN_SWITCH_NAMES_STRING", 452);
      sXe = new a("USERINFO_BACKGROUND_CALC_TIME_LONG", 453);
      sXf = new a("USERINFO_WELAB_LAST_UPDATE_TIME_LONG", 454);
      sXg = new a("USERINFO_WELAB_UPDATE_TIME_INTERVAL_INT", 455);
      sXh = new a("USERINFO_WELAB_SERVER_TIMESTAMP_INT", 456);
      sXi = new a("USERINFO_WELAB_REDPOINT_STRING", 457);
      sXj = new a("USERINFO_WELAB_APP_REDPOINT_STRING", 458);
      sXk = new a("USERINFO_WENOTE_KEEP_TOP_DATA_STRING_SYNC", 459);
      sXl = new a("BUSINESS_OFFLINE_GETMSG_INTERVAL_INT", 460);
      sXm = new a("BUSINESS_OFFLINE_GETMSG_ACK_KEY_STRING", 461);
      sXn = new a("BUSINESS_OFFLINE_GETMSG_MAX_POS_TIME_INT", 462);
      sXo = new a("USERINFO_WALLET_HK_PAY_URL_STRING", 463);
      sXp = new a("USERINFO_SUPPORT_HEVC_VIDEO_INT", 464);
      sXq = new a("USERINFO_HAD_PRELOAD_SIZE_LONG", 465);
      sXr = new a("USERINFO_HAD_PRELOAD_TIME_LONG", 466);
      sXs = new a("USERINFO_C2C_HAD_PRELOAD_COUNT_INT", 467);
      sXt = new a("USERINFO_SNS_HAD_PRELOAD_COUNT_INT", 468);
      sXu = new a("USERINFO_CHATTING_MONITOR_MAIN_WORDING_STRING_SYNC", 469);
      sXv = new a("USERINFO_CHATTING_MONITOR_MAIN_URL_STRING_SYNC", 470);
      sXw = new a("USERINFO_CHATTING_MONITOR_MAIN_INTERVAL_LONG_SYNC", 471);
      sXx = new a("USERINFO_CHATTING_MONITOR_MAIN_CLOSABLE_BOOLEAN_SYNC", 472);
      sXy = new a("USERINFO_CHATTING_MONITOR_MAIN_AUTOTRIGGER_BOOLEAN_SYNC", 473);
      sXz = new a("USERINFO_CHATTING_BANNER_CLOSED_BOOLEAN_SYNC", 474);
      sXA = new a("USERINFO_MAIN_MONITOR_MAIN_WORDING_STRING_SYNC", 475);
      sXB = new a("USERINFO_MAIN_MONITOR_MAIN_URL_STRING_SYNC", 476);
      sXC = new a("USERINFO_MAIN_MONITOR_MAIN_INTERVAL_LONG_SYNC", 477);
      sXD = new a("USERINFO_MAIN_MONITOR_MAIN_CLOSABLE_BOOLEAN_SYNC", 478);
      sXE = new a("USERINFO_MAIN_MONITOR_MAIN_AUTOTRIGGER_BOOLEAN_SYNC", 479);
      sXF = new a("USERINFO_MAIN_BANNER_CLOSED_BOOLEAN_SYNC", 480);
      sXG = new a("USERINFO_MONITOR_BANNER_MSG_COME_TIME_TICKS_LONG_SYNC", 481);
      sXH = new a("USERINFO_MONITOR_IS_TRIGGERED_BOOLEAN_SYNC", 482);
      sXI = new a("USERINFO_RECENT_LAUNCH_AA_GROUP_STRING_SYNC", 483);
      sXJ = new a("USERINFO_WALLET_ENTRY_REDDOT_PUSH_DATE_LONG_SYNC", 484);
      sXK = new a("USERINFO_WALLET_INDEX_MAIDAN_STRING_SYNC", 485);
      sXL = new a("USERINFO_LQT_WALLET_RED_DOT_WORDING_STRING", 486);
      sXM = new a("USERINFO_LQT_WALLET_RED_DOT_INT", 487);
      sXN = new a("USERINFO_LQT_BALANCE_RED_DOT_INT", 488);
      sXO = new a("USERINFO_LQT_LINK_RED_DOT_INT", 489);
      sXP = new a("USERINFO_LQB_MALL_ENTRY_RED_DOT_INT", 490);
      sXQ = new a("USERINFO_WEPKG_CHECK_DOWNLOAD_TIME_LONG", 491);
      sXR = new a("USERINFO_WEPKG_FRONT_TRIGGER_DOWNLOAD_TIME_LONG", 492);
      sXS = new a("USERINFO_WEPKG_ENTRANCE_TRIGGER_DOWNLOAD_TIME_LONG", 493);
      sXT = new a("USERINFO_GAME_SILENT_DOWNLOAD_TIME_LONG", 494);
      sXU = new a("USERINFO_FTS_MASTER_DB_VERISON_INT_SYNC", 495);
      sXV = new a("USERINFO_FTS_MASTER_DB_CORRUPT_REBUILD_TIME_INT_SYNC", 496);
      sXW = new a("USERINFO_TINKER_BOOTS_CHECK_LAST_TIME_LONG", 497);
      sXX = new a("BUSINESS_OFFLINE_GETMSG_REQ_KEY_STRING", 498);
      sXY = new a("BUSINESS_OFFLINE_GETMSG_PAYMSG_TYPE_INT", 499);
      sXZ = new a("BUSINESS_OFFLINE_GETMSG_TRANS_ID_STRING", 500);
      sYa = new a("USERINFO_FTS_DISCOVERY_RED_ID_INT", 501);
      sYb = new a("USERINFO_FTS_DISCOVERY_RED_XML_STRING", 502);
      sYc = new a("NEW_BANDAGE_DATASOURCE_WALLET_MORE_TAB_STRING_SYNC", 503);
      sYd = new a("NEW_BANDAGE_DATASOURCE_WALLET_BANKCARD_STRING_SYNC", 504);
      sYe = new a("NEW_BANDAGE_WATCHER_WALLET_COMMON_STRING_SYNC", 505);
      sYf = new a("USERINFO_WALLET_MORE_TAB_REDDOT_WORDING_STRING_SYNC", 506);
      sYg = new a("USERINFO_WALLET_BANKCARD_SERIAL_STRING_SYNC", 507);
      sYh = new a("USERINFO_CALC_WX_SCAN_STEP_INT", 508);
      sYi = new a("USERINFO_CALC_WX_SCAN_CURR_MSGID2_LONG", 509);
      sYj = new a("USERINFO_CALC_WX_SCAN_MAX_MSGID2_LONG", 510);
      sYk = new a("USERINFO_CALC_WX_SCAN_REPORT_TIME_LONG", 511);
      sYl = new a("USERINFO_CALC_WX_SCAN_START_TIME_LONG", 512);
      sYm = new a("USERINFO_CALC_WX_SCAN_FINISH_TIME_LONG", 513);
      sYn = new a("USERINFO_CALC_WX_SCAN_SHOW_FILE_INT", 514);
      sYo = new a("USERINFO_WALLET_F2F_COLLECT_PAY_URL_STRING_SYNC", 515);
      sYp = new a("USERINFO_WALLET_F2F_COLLECT_TRUE_NAME_STRING_SYNC", 516);
      sYq = new a("USERINFO_WALLET_F2F_COLLECT_BOTTOM_MENU_STRING_SYNC", 517);
      sYr = new a("USERINFO_WALLET_F2F_COLLECT_BOTTOM_LEFT_ICON_URL_STRING_SYNC", 518);
      sYs = new a("USERINFO_WALLET_F2F_COLLECT_UPRIGHT_MENU_STRING_SYNC", 519);
      sYt = new a("USERINFO_WALLET_BIND_CARD_MENU_STRING_SYNC", 520);
      sYu = new a("USERINFO_WALLET_FACING_REDDOT_WORDING_STRING_SYNC", 521);
      sYv = new a("USERINFO_HARDWARE_LAST_UPLOAD_TICKS_LONG_SYNC", 522);
      sYw = new a("USERINFO_WALLET_LQT_OPEN_FLAG_INT_SYNC", 523);
      sYx = new a("USERINFO_WALLET_LQT_ENTRY_WORDING_STRING_SYNC", 524);
      sYy = new a("USERINFO_WALLET_SET_PWD_TIP_INT_SYNC", 525);
      sYz = new a("USERINFO_WALLETLOCK_CURRENT_USED_TYPE_INT_SYNC", 526);
      sYA = new a("USERINFO_WALLETLOCK_FINGERPRINT_IS_OPENED_BOOLEAN_SYNC", 527);
      sYB = new a("USERINFO_WALLETLOCK_FINGERPRINT_FID_LIST_STRING_SYNC", 528);
      sYC = new a("USERINFO_WALLETLOCK_GESTURE_IS_OPENED_BOOLEAN_SYNC", 529);
      sYD = new a("USERINFO_WALLETLOCK_FINGERPRINT_LAST_VERIFY_OK_TIME_STRING_SYNC", 530);
      sYE = new a("USERINFO_WALLETLOCK_FINGERPRINT_LAST_BLOCK_TIME_STRING_SYNC", 531);
      sYF = new a("USERINFO_WALLETLOCK_IS_AUTO_JUMP_TO_GESTURE_WHEN_NOT_SUPPORT_FINGERPRINT_BOOLEAN_SYNC", 532);
      sYG = new a("USERINFO_WALLETLOCK_CURRENT_JSON_TYPE_STRING_SYNC", 533);
      sYH = new a("USERINFO_WALLET_USERINFO_UNREGTITLE_TYPE_STRING_SYNC", 534);
      sYI = new a("USERINFO_WALLET_USERINFO_UNREGURL_TYPE_STRING_SYNC", 535);
      sYJ = new a("USERINFO_WCPAY_WALLET_BUFFER_CN_STRING_SYNC", 536);
      sYK = new a("USERINFO_WCPAY_WALLET_BUFFER_MY_STRING_SYNC", 537);
      sYL = new a("USERINFO_WCPAY_WALLET_BUFFER_ZA_STRING_SYNC", 538);
      sYM = new a("USERINFO_WCPAY_WALLET_BUFFER_HK_STRING_SYNC", 539);
      sYN = new a("USERINFO_WALLET_QR_REWARD_PHOTO_WIDTH_INT_SYNC", 540);
      sYO = new a("USERINFO_WALLET_QR_REWARD_ICON_WIDTH_INT_SYNC", 541);
      sYP = new a("USERINFO_WALLET_QR_REWARD_WORD_STRING_SYNC", 542);
      sYQ = new a("USERINFO_WALLET_QR_REWARD_DESC_STRING_SYNC", 543);
      sYR = new a("USERINFO_WALLET_QR_REWARD_TRUE_NAME_STRING_SYNC", 544);
      sYS = new a("USERINFO_WALLET_QR_REWARD_MAX_AMT_INT_SYNC", 545);
      sYT = new a("USERINFO_WALLET_QR_REWARD_AMT_LIST_STRING_SYNC", 546);
      sYU = new a("USERINFO_WALLET_QR_REWARD_BOTTOM_STR_STRING_SYNC", 547);
      sYV = new a("USERINFO_WALLET_QR_REWARD_BOTTOM_URL_STRING_SYNC", 548);
      sYW = new a("USERINFO_WALLET_QR_REWARD_LAST_PHOTO_URL_STRING_SYNC", 549);
      sYX = new a("USERINFO_SHOW_MSG_DELAY_BOOLEAN_SYNC", 550);
      sYY = new a("USERINFO_WALLET_COLLECT_BUSITYPE_INT_SYNC", 551);
      sYZ = new a("USERINFO_WALLET_COLLECT_BUSIURL_STRING_SYNC", 552);
      sZa = new a("USERINFO_SETTING_SWITCH_ACCOUNT_FIRST_CLICK_BOOLEAN_SYNC", 553);
      sZb = new a("GAME_FIND_MORE_FRIEND_MSG_ID_STRING_SYNC", 554);
      sZc = new a("NEW_BANDAGE_DATASOURCE_GROUP_PAY_STRING_SYNC", 555);
      sZd = new a("NEW_BANDAGE_DATASOURCE_F2F_COLLECT_STRING_SYNC", 556);
      sZe = new a("NEW_BANDAGE_DATASOURCE_F2F_HB_STRING_SYNC", 557);
      sZf = new a("NEW_BANDAGE_DATASOURCE_QR_REWARD_STRING_SYNC", 558);
      sZg = new a("NEW_BANDAGE_DATASOURCE_BANK_REMIT_STRING_SYNC", 559);
      sZh = new a("USERINFO_PAY_OR_RECV_HAS_SHOW_RED_DOT_BOOLEAN_SYNC", 560);
      sZi = new a("USERINFO_WALLET_BANK_REMIT_MIN_POUNDAGE_INT_SYNC", 561);
      sZj = new a("USERINFO_WALLET_BANK_REMIT_MAX_TRANSFER_AMOUNT_INT_SYNC", 562);
      sZk = new a("USERINFO_WALLET_BANK_REMIT_PAYLIST_STRING_SYNC", 563);
      sZl = new a("USERINFO_WALLET_BANK_REMIT_OPEN_INT_SYNC", 564);
      sZm = new a("USERINFO_WALLET_BANK_REMIT_HAS_SHOWN_RED_DOT_INT_SYNC", 565);
      sZn = new a("USERINFO_WALLET_MENU_UI_REDDOT_CONFIG_STRING_SYNC", 566);
      sZo = new a("USERINFO_WALLET_MALL_MENU_UI_REDDOT_CONFIG_BOOLEAN_SYNC", 567);
      sZp = new a("USERINFO_CELLTEXTVIEW_CONFIG_BOOLEAN_SYNC", 568);
      sZq = new a("USERINFO_APPBRANDRECENTVIEW_CONFIG_BOOLEAN_SYNC", 569);
      sZr = new a("USERINFO_WALLET_BALANCE_MENU_INFO_STRING_SYNC", 570);
      sZs = new a("USERINFO_WALLET_ENTRY_WORDING_STRING_SYNC", 571);
      sZt = new a("USERINFO_WALLET_MY_ENTRY_TAB_REDDOT_BOOLEAN_SYNC", 572);
      sZu = new a("USERINFO_WALLET_MY_ENTRY_REDDOT_BOOLEAN_SYNC", 573);
      sZv = new a("USERINFO_LQT_DEFAULTCARD_STRING_SYNC", 574);
      sZw = new a("USERINFO_LQT_DEFAULTCARD_SAVE_STRING_SYNC", 575);
      sZx = new a("USERINFO_LQT_DEFAULTCARD_FETCH_STRING_SYNC", 576);
      sZy = new a("USERINFO_HARDWARE_CPU_FREQUENCY_MHZ_INT_SYNC", 577);
      sZz = new a("USERINFO_HARDWARE_MEMORY_IN_MB_INT_SYNC", 578);
    }
    
    private a() {}
  }
}


/* Location:              /Users/Han/Desktop/wxall/微信反编译/反编译 6.6.7/dex2jar-2.0/classes-dex2jar.jar!/com/tencent/mm/storage/aa.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */