package com.tencent.liteav.basic.datareport;

public class a
{
  public static String A;
  public static String B;
  public static String C;
  public static int D;
  public static int E;
  public static int F;
  public static int G;
  public static int H;
  public static int I;
  public static int J;
  public static int K;
  public static int L;
  public static int M;
  public static int N;
  public static int O;
  public static int P;
  public static int Q;
  public static int R;
  public static int S;
  public static int T;
  public static int U;
  public static int V;
  public static int W;
  public static int X;
  public static int Y;
  public static int Z;
  public static String a = "u32_module_id";
  public static int aA = 1009;
  public static int aB = 1010;
  public static int aC = 1011;
  public static int aD = 1012;
  public static int aE = 1013;
  public static int aF = 1014;
  public static int aG = 1015;
  public static int aH = 1997;
  public static int aI = 1998;
  public static int aJ = 1999;
  public static int aK = 1301;
  public static int aL = 1;
  public static int aM = 1;
  public static int aN = 2;
  public static int aO = 3;
  public static int aa;
  public static int ab;
  public static int ac;
  public static int ad;
  public static int ae;
  public static int af;
  public static int ag;
  public static int ah;
  public static int ai;
  public static int aj;
  public static int ak;
  public static int al;
  public static int am;
  public static int an;
  public static int ao;
  public static int ap;
  public static int aq;
  public static int ar;
  public static int as;
  public static int at;
  public static int au;
  public static int av;
  public static int aw;
  public static int ax;
  public static int ay;
  public static int az;
  public static String b = "str_stream_url";
  public static String c = "platform";
  public static String d = "biz_id";
  public static String e = "app_id";
  public static String f = "dev_type";
  public static String g = "net_type";
  public static String h = "dev_id";
  public static String i = "dev_uuid";
  public static String j = "app_name";
  public static String k = "app_version";
  public static String l = "sys_version";
  public static String m = "mac_addr";
  public static String n = "evt_comm";
  public static String o = "event_id";
  public static String p = "err_code";
  public static String q = "err_info";
  public static String r = "ext";
  public static String s = "event_id";
  public static String t = "err_code";
  public static String u = "err_info";
  public static String v = "file_size";
  public static String w = "up_usetime";
  public static String x = "up_ip";
  public static String y = "ugc_upload";
  public static String z = "DAU";
  
  static
  {
    A = "u32_error_code";
    B = "str_error_msg";
    C = "str_msg_more";
    D = 1000;
    E = 1001;
    F = 1002;
    G = 2001;
    H = 2002;
    I = 2003;
    J = 2004;
    K = 2005;
    L = 2006;
    M = 2007;
    N = 2008;
    O = 2009;
    P = 40001;
    Q = 40000;
    R = 40002;
    S = 40003;
    T = 40101;
    U = 40100;
    V = 40102;
    W = 40501;
    X = 40500;
    Y = 40502;
    Z = 40201;
    aa = 40200;
    ab = 40202;
    ac = 40301;
    ad = 40401;
    ae = 40402;
    af = 49999;
    ag = 1000;
    ah = 1001;
    ai = 1002;
    aj = 1003;
    ak = 1004;
    al = 1005;
    am = 1006;
    an = 1007;
    ao = 1008;
    ap = 1009;
    aq = 1010;
    ar = 1011;
    as = 1001;
    at = 1002;
    au = 1003;
    av = 1004;
    aw = 1005;
    ax = 1006;
    ay = 1007;
    az = 1008;
  }
}


/* Location:              /Users/Han/Desktop/wxall/微信反编译/反编译 6.6.7/dex2jar-2.0/classes2-dex2jar.jar!/com/tencent/liteav/basic/datareport/a.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */